### ISSUE TITLE
use system jemalloc

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [bsc-pm/nanos6#7]
Is it possible to use system jemalloc?
Why it need jemalloc built with the `nanos6_je_` prefix?

**Comment by kevinsala** [comment]
The idea is to have a jemalloc only for the Nanos6 library to not interfere with the allocations made by the application. Additionally, the jemalloc installation for Nanos6 must be compiled with `--enable-stats` a part from the nanos6 prefix (`--with-jemalloc-prefix=nanos6_je_`).

**Comment by Alessandro-Barbieri** [comment]
`--enable-stats` is on by default on jemalloc since a long time
